### ISSUE TITLE
Erron running script in ubuntu 22.04

### ISSUE THREAD

**Issue by anilsathyan7** [CarlosDev314159/d-link-dwa-171-wifi-adapter-automatic-driver-installer#1]
home/anilsathyan7/rtl8812au/core/rtw_br_ext.c:25:10: fatal error: net/ipx.h: No such file or directory
   25 | #include <net/ipx.h>
      |          ^~~~~~~~~~~
compilation terminated.
make[2]: *** [scripts/Makefile.build:297: /home/anilsathyan7/rtl8812au/core/rtw_br_ext.o] Error 1
make[1]: *** [Makefile:1909: /home/anilsathyan7/rtl8812au] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.15.0-84-generic'
make: *** [Makefile:1077: modules] Error 2

**Comment by CarlosSenobio** [comment]
Thank you for your report. I will fix it and update the file.
